name: Deploy Shorten Platform (Bitunix & GetMyTrade)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [bitunix, getmytrade]

    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set NPM mirror
        run: npm config set registry https://registry.npmmirror.com

      - name: Setup environment file
        run: |
          if [ "${{ matrix.target }}" = "bitunix" ]; then
            echo "Using .env.production as-is"
          elif [ "${{ matrix.target }}" = "getmytrade" ]; then
            cp .env.mytrade .env.production
          fi

      - name: Install Dependencies
        run: |
          for i in 1 2 3; do
            npm install --legacy-peer-deps && break
            echo "Retrying npm install ($i)..."
            sleep 5
          done

      - name: Reset NPM registry
        run: npm config set registry https://registry.npmjs.org

      - name: Build Project
        run: npm run build

      - name: Deploy via SSH
        run: |
          if [ "${{ matrix.target }}" = "bitunix" ]; then
            sshpass -p 'c#)rgPMzNC2998@Vb4.M' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@147.93.30.80:/var/www/shrt-bitunix-fe/
          elif [ "${{ matrix.target }}" = "getmytrade" ]; then
            sshpass -p '5G&ZZoT6B1jH)f?bC&j9' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@156.67.221.244:/var/www/getmytrade-fe/
          fi

      - name: Set Permissions
        run: |
          if [ "${{ matrix.target }}" = "bitunix" ]; then
            sshpass -p 'c#)rgPMzNC2998@Vb4.M' ssh -o StrictHostKeyChecking=no root@147.93.30.80 '
              chmod -R 755 /var/www/shrt-bitunix-fe &&
              chown -R www-data:www-data /var/www/shrt-bitunix-fe
            '
          elif [ "${{ matrix.target }}" = "getmytrade" ]; then
            sshpass -p '5G&ZZoT6B1jH)f?bC&j9' ssh -o StrictHostKeyChecking=no root@156.67.221.244 '
              chmod -R 755 /var/www/getmytrade-fe &&
              chown -R www-data:www-data /var/www/getmytrade-fe
            '
          fi

      - name: Restart Services
        run: |
          if [ "${{ matrix.target }}" = "bitunix" ]; then
            sshpass -p 'c#)rgPMzNC2998@Vb4.M' ssh -o StrictHostKeyChecking=no root@147.93.30.80 '
              systemctl restart nginx
              pm2 restart bitunix
            '
          elif [ "${{ matrix.target }}" = "getmytrade" ]; then
            sshpass -p '5G&ZZoT6B1jH)f?bC&j9' ssh -o StrictHostKeyChecking=no root@156.67.221.244 '
              systemctl restart nginx
              pm2 restart getmytrade-fe
            '
          fi
